local a = DD(SymbolExpression("x") * SymbolExpression("y"), SymbolExpression("x"))
local b = DD(Integer(3) * SymbolExpression("x") ^ Integer(2) + Integer(2) * SymbolExpression("x") + Integer(6), SymbolExpression("x"))
local c = DD(E ^ SymbolExpression("x"), SymbolExpression("x"))
local d = DD(FunctionExpression("f", {SymbolExpression("x") ^ Integer(2)}))
local e = DD(SymbolExpression("x") ^ SymbolExpression("x"))
local f = DD(PolynomialRing({Integer(3), Integer(4), Integer(5)}, "x"))
local g = DD(LN(SymbolExpression("y")), SymbolExpression("y"))
local h = DD(SymbolExpression("x") ^ SymbolExpression("n"))
local i = DD(SIN((SymbolExpression("x"))));
local j = DD(SIN(Integer(2) * COS(SymbolExpression("x"))));
local k = DD(ARCTAN(SymbolExpression("x") ^ (Integer(1) / Integer(2))))
local l = DD(ARCSEC(SymbolExpression("x")))

starttest("derivatives")

test(a, "(d/dx (x * y))")
test(a:autosimplify(), "y", a)
test(b:autosimplify(), "(2 + (6 * x))", b)
test(c:autosimplify(), "(e ^ x)", c)
test(d:autosimplify(), "(2 * x * f'((x ^ 2)))", d)
test(e:autosimplify(), "((x ^ x) * (1 + log(e, x)))", e)
test(f:autosimplify(), "(4 + (10 * x))", f)
test(g:autosimplify(), "(y ^ -1)", g)
test(h:autosimplify(), "(n * (x ^ (-1 + n)))", h)
test(i:autosimplify(), "cos(x)", i)
test(j:autosimplify(), "(-2 * cos((2 * cos(x))) * sin(x))", j)
test(k:autosimplify(), "(1/2 * (x ^ -1/2) * ((1 + x) ^ -1))", k)
test(l:autosimplify(), "((|x| ^ -1) * ((1 + (-1 * (x ^ 2))) ^ -1/2))", l)

endtest()