local a = dparse("int(x^2, x)")
local b = dparse("int(x^-1, x, 1, e)")
local c = dparse("int(3*x^2+2*x+6, x)")
local d = dparse("int(sin(x)*cos(x), x)")
local e = dparse("int(2*x*cos(x^2), x)")

starttest("integration")
test(a, "int((x ^ 2), x)")
test(a:autosimplify(), "(1/3 * (x ^ 3))", a)
test(b:autosimplify(), "1", b)
test(c:autosimplify(), "((6 * x) + (x ^ 2) + (x ^ 3))", c)
test(d:autosimplify(), "(-1/2 * (cos(x) ^ 2))", d)
test(e:autosimplify(), "sin((x ^ 2))", e)
endtest()