%% LaTeX2e file `myfile.lua'
%% generated by the `filecontents' environment
%% from source `charlie' on 2022/08/09.
%%
    function Expression:mycombine()
        local a = self.expressions[1].expressions[1].expressions[1]
        local b = self.expressions[1].expressions[1].expressions[2]
        local c = self.expressions[1].expressions[2].expressions[1]
        local d = self.expressions[1].expressions[2].expressions[2]
        local numerator = a*d-b*c
        local denominator = self.expressions[2]*b*d
        return numerator/denominator
    end

    function Expression:simplifynum()
        local a = self.expressions[1]
        local b = self.expressions[2]
        a = simplify(a)
        return a/b
    end

    function Expression:factornum()
        local a = self.expressions[1]
        local b = self.expressions[2]
        a = factor(a)
        return a/b
    end
